[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "document-intelligence-cli"
version = "0.1.0"
description = "A CLI tool for extracting structured information from text documents."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Michael BAG", email= "michaelbag8@gmail.com" }
]
license = { text = "MIT" }
dependencies = []

[project.scripts]
docintel = "docintel.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]